# 不使用全局 events，自己定义
events {
    worker_connections 1024;
}

http {
    # 关闭日志（可选）
    access_log off;
    error_log stderr;

    # MIME 类型
    include /opt/homebrew/etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 8080;               # 本项目专用端口
        server_name localhost;

        # 托管前端静态资源
        location / {
            root /Users/00513436/Desktop/study/aniyajs/aniyajs-app/docs;  # 👈 必须是绝对路径！
            index index.html;
            try_files $uri $uri/ /index.html;  # 支持 SPA 路由
        }

        # # 可选：代理 API 到本地 NestJS（如 3000 端口）
        # location /api/ {
        #     proxy_pass http://localhost:8889/;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }
    }
}